name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MoralSupport.Tasks/Web/MoralSupport.Tasks.Web.csproj

    - name: Build project
      run: dotnet build MoralSupport.Tasks/Web/MoralSupport.Tasks.Web.csproj --configuration Release

    - name: Publish Razor Pages
      run: dotnet publish MoralSupport.Tasks/Web/MoralSupport.Tasks.Web.csproj --configuration Release --output publish

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish/wwwroot
        publish_branch: gh-pages
        force_orphan: true
